//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("Ok", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class OkType {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceFilterByKeywordsSpec))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ResourceFilterByTopicSpec))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
public abstract partial class ResourceFilterSpecParametersBaseType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
public partial class ResourceFilterByKeywordsSpec : ResourceFilterSpecParametersBaseType {
    
    private AssociationTagInfoType[] associationTagsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
    public AssociationTagInfoType[] AssociationTags {
        get {
            return this.associationTagsField;
        }
        set {
            this.associationTagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
public partial class AssociationTagInfoType {
    
    private string wordField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Word {
        get {
            return this.wordField;
        }
        set {
            this.wordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
public partial class ResourceFilterByTopicSpec : ResourceFilterSpecParametersBaseType {
    
    private long topicIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long TopicId {
        get {
            return this.topicIdField;
        }
        set {
            this.topicIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("RegisterSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class RegisterSpecType {
    
    private string loginField;
    
    private string passwordField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("RequestActivationSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class RequestActivationSpecType {
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ChangePasswordSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ChangePasswordSpecType {
    
    private string newPasswordField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewPassword {
        get {
            return this.newPasswordField;
        }
        set {
            this.newPasswordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ChangeEmailSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ChangeEmailSpecType {
    
    private string passwordField;
    
    private string oldEmailField;
    
    private string newEmailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OldEmail {
        get {
            return this.oldEmailField;
        }
        set {
            this.oldEmailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NewEmail {
        get {
            return this.newEmailField;
        }
        set {
            this.newEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ResetPasswordSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ResetPasswordSpecType {
    
    private string loginField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("LoginSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class LoginSpecType {
    
    private string loginField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ProfileFootprintInfo", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ProfileFootprintInfoType {
    
    private string loginField;
    
    private string emailFootprintField;
    
    private bool isActivatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Login {
        get {
            return this.loginField;
        }
        set {
            this.loginField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EmailFootprint {
        get {
            return this.emailFootprintField;
        }
        set {
            this.emailFootprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsActivated {
        get {
            return this.isActivatedField;
        }
        set {
            this.isActivatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("CreateTopicSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class CreateTopicSpecType {
    
    private AssociationTagInfoType[] associationTagsField;
    
    private string topicNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
    public AssociationTagInfoType[] AssociationTags {
        get {
            return this.associationTagsField;
        }
        set {
            this.associationTagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TopicName {
        get {
            return this.topicNameField;
        }
        set {
            this.topicNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("TopicsList", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class TopicsListType {
    
    private TopicInfoType[] itemsField;
    
    private int countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Topic")]
    public TopicInfoType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("TopicInfo", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class TopicInfoType {
    
    private AssociationTagInfoType[] associationTagsField;
    
    private string titleField;
    
    private long idField;
    
    private bool isActiveField;
    
    private long totalContentPartsField;
    
    private bool totalContentPartsFieldSpecified;
    
    private long learnedContentPartsField;
    
    private bool learnedContentPartsFieldSpecified;
    
    private long deliveryIntervalSecondsField;
    
    private bool deliveryIntervalSecondsFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
    public AssociationTagInfoType[] AssociationTags {
        get {
            return this.associationTagsField;
        }
        set {
            this.associationTagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsActive {
        get {
            return this.isActiveField;
        }
        set {
            this.isActiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long TotalContentParts {
        get {
            return this.totalContentPartsField;
        }
        set {
            this.totalContentPartsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotalContentPartsSpecified {
        get {
            return this.totalContentPartsFieldSpecified;
        }
        set {
            this.totalContentPartsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long LearnedContentParts {
        get {
            return this.learnedContentPartsField;
        }
        set {
            this.learnedContentPartsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LearnedContentPartsSpecified {
        get {
            return this.learnedContentPartsFieldSpecified;
        }
        set {
            this.learnedContentPartsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long DeliveryIntervalSeconds {
        get {
            return this.deliveryIntervalSecondsField;
        }
        set {
            this.deliveryIntervalSecondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeliveryIntervalSecondsSpecified {
        get {
            return this.deliveryIntervalSecondsFieldSpecified;
        }
        set {
            this.deliveryIntervalSecondsFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ActivateTopicSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ActivateTopicSpecType {
    
    private long dueSecondsField;
    
    private long intervalSecondsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long DueSeconds {
        get {
            return this.dueSecondsField;
        }
        set {
            this.dueSecondsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long IntervalSeconds {
        get {
            return this.intervalSecondsField;
        }
        set {
            this.intervalSecondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ResourceFilterSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ResourceFilterSpecType {
    
    private ResourceFilterSpecParametersBaseType itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ByKeywords", typeof(ResourceFilterByKeywordsSpec))]
    [System.Xml.Serialization.XmlElementAttribute("ByTopic", typeof(ResourceFilterByTopicSpec))]
    public ResourceFilterSpecParametersBaseType Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("CreateResourceSpec", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class CreateResourceSpecType {
    
    private AssociationTagInfoType[] associationTagsField;
    
    private string resourceTitleField;
    
    private string resourceUrlField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
    public AssociationTagInfoType[] AssociationTags {
        get {
            return this.associationTagsField;
        }
        set {
            this.associationTagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResourceTitle {
        get {
            return this.resourceTitleField;
        }
        set {
            this.resourceTitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResourceUrl {
        get {
            return this.resourceUrlField;
        }
        set {
            this.resourceUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ResourcesList", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ResourcesListType {
    
    private ResourceInfoType[] itemsField;
    
    private int countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Resource")]
    public ResourceInfoType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ResourceInfo", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ResourceInfoType {
    
    private AssociationTagInfoType[] associationTagsField;
    
    private string titleField;
    
    private string urlField;
    
    private bool isValidatedField;
    
    private bool isMyResourceField;
    
    private long idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
    public AssociationTagInfoType[] AssociationTags {
        get {
            return this.associationTagsField;
        }
        set {
            this.associationTagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string Url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsValidated {
        get {
            return this.isValidatedField;
        }
        set {
            this.isValidatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsMyResource {
        get {
            return this.isMyResourceField;
        }
        set {
            this.isMyResourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ContentPartsList", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ContentPartsListType {
    
    private ContentPartInfoType[] itemsField;
    
    private int countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ContentPart")]
    public ContentPartInfoType[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ContentPartInfo", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ContentPartInfoType {
    
    private string textField;
    
    private long orderField;
    
    private long resourceIdField;
    
    private long idField;
    
    private bool isDeliveredField;
    
    private bool isLearnedField;
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long ResourceId {
        get {
            return this.resourceIdField;
        }
        set {
            this.resourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsDelivered {
        get {
            return this.isDeliveredField;
        }
        set {
            this.isDeliveredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool IsLearned {
        get {
            return this.isLearnedField;
        }
        set {
            this.isLearnedField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedErrorInfoType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
[System.Xml.Serialization.XmlRootAttribute("ErrorInfo", Namespace="MicroLearningSvc", IsNullable=false)]
public partial class ErrorInfoType {
    
    private string messageField;
    
    private string stackTraceField;
    
    private ErrorInfoType innerErrorField;
    
    private string typeNameField;
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public string StackTrace {
        get {
            return this.stackTraceField;
        }
        set {
            this.stackTraceField = value;
        }
    }
    
    /// <remarks/>
    public ErrorInfoType InnerError {
        get {
            return this.innerErrorField;
        }
        set {
            this.innerErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypeName {
        get {
            return this.typeNameField;
        }
        set {
            this.typeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MicroLearningSvc")]
public partial class ExtendedErrorInfoType : ErrorInfoType {
    
    private string rawErrorInfoField;
    
    /// <remarks/>
    public string RawErrorInfo {
        get {
            return this.rawErrorInfoField;
        }
        set {
            this.rawErrorInfoField = value;
        }
    }
}
